server:
  port: ${SERVER_PORT:8082}

bpmn-engine-proxy:
  uri: http://${BPMN_ENGINE_PROXY_HOST:213.108.129.175}:${BPMN_ENGINE_PROXY_PORT:8090}

spring:
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    properties.hibernate.default_schema: task
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:213.108.129.175}:${DB_PORT:5432}/${DATABASE:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:transneft}
    driver-class-name: org.postgresql.Driver
#  sql.init:
#    mode: always
#    encoding: UTF-8
