server:
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true

spring:
  application.name: task-service
  profiles:
    active: dev, dev-postgres
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: task
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
#  sql.init:
#    mode: always
#    encoding: UTF-8

rsql:
  defaultSort: ${DEFAULT_SORT:createdAt,asc}
  defaultPageSize: ${DEFAULT_PAGE_SIZE:10}
